import { OwnedResource } from "@libutil/allocator";
import { vec2 } from "gl-matrix";

/**
 * Collision data struct. Generated by collision methods in {@link collisiondetection.ts}
 *
 * Collisions have a (contextual) primary and secondary collision object - the collision will be
 *  a line from a point on the surface of A to a point on the surface of B which represents the
 *  maximum collision that is occurring between the two objects.
 * CollisionPoint: The point on the surface of object A
 * CollisionNormal: The direction of the collision
 * CollisionDepth: The length of the line from collision point on A to collision point on B
 */
export type CollisionData = {
  CollisionPoint: OwnedResource<vec2>,
  CollisionNormal: OwnedResource<vec2>,
  CollisionDepth: number,
};
